# Generated by Django 5.0.3 on 2024-09-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nome_do_cargo', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('skills', models.TextField(max_length=500)),
            ],
            options={
                'db_table': 'webapp_cargos',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='login',
            options={'managed': False},
        ),
    ]
