# Generated by Django 5.0.3 on 2024-10-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_cargo_alter_login_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nome_do_funcionario', models.CharField(max_length=100)),
                ('cargo_id', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
                ('certificados', models.TextField(max_length=2000)),
            ],
            options={
                'db_table': 'webapp_funcionarios',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='login',
            table='webapp_login',
        ),
    ]
