# Generated by Django 5.0.3 on 2024-10-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_funcionario_alter_login_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nome_skills', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'webapp_skills',
                'managed': False,
            },
        ),
    ]
