# Generated by Django 5.0.3 on 2024-10-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('funcionario_id', models.CharField(max_length=50)),
                ('nome_skill', models.CharField(max_length=25)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
            ],
            options={
                'db_table': 'webapp_cursos',
                'managed': False,
            },
        ),
    ]
